import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, PackageSearch, ShieldCheck, Sparkles } from "lucide-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { Link } from "react-router-dom";

const metrics = [
 {label:"Pedidos encontrados",value:154,delta:"+12%",tone:"dark"}, {label:"Clientes House 190",value:93,delta:"60% do total",tone:"brand"},
 {label:"Elegíveis para contato",value:81,delta:"87% aprovados",tone:"light"}, {label:"Mensagens enviadas",value:76,delta:"5 aguardando",tone:"light"},
];
const chart = [{day:"22 ago",value:48},{day:"23 ago",value:58},{day:"24 ago",value:52},{day:"25 ago",value:69},{day:"26 ago",value:72},{day:"27 ago",value:81}];
const funnel = [["Pedidos Takeat",154,"100%"],["Clientes identificados",127,"82%"],["Marca House 190",93,"73%"],["Telefone e regras OK",81,"87%"]];

export function DashboardPage() { return <div className="mx-auto max-w-[1440px] p-5 md:p-8 xl:p-10">
  <section className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] text-black/38"><Sparkles className="size-3.5 text-[#d49300]" />Sexta, 28 de agosto</div><h1 className="text-3xl font-semibold tracking-[-.045em] md:text-[40px]">Bom dia, Gleuce <span className="inline-block origin-bottom-right rotate-[-8deg]">👋</span></h1><p className="mt-2 text-sm text-black/48">O pós-venda de ontem está pronto para sua revisão.</p></div><div className="flex gap-2"><Link to="/clientes-ontem" className="rounded-xl border border-black/10 bg-white px-4 py-2.5 text-xs font-semibold">Ver excluídos</Link><Link to="/fila" className="group flex items-center gap-2 rounded-xl bg-[#171719] px-4 py-2.5 text-xs font-semibold text-white shadow-lg shadow-black/10">Revisar 81 clientes <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" /></Link></div></section>
  <div className="mt-7 flex items-center gap-2 rounded-2xl border border-[#e5ae25]/35 bg-[#fff7dc] px-4 py-3 text-xs text-[#765506]"><AlertTriangle className="size-4 shrink-0" /><strong>DRY RUN ativo.</strong><span className="text-[#765506]/75">Nenhuma mensagem real pode ser enviada enquanto você valida a operação.</span></div>
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><MetricCard key={m.label} {...m}/>)}</section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.85fr]"><div className="rounded-[22px] border border-black/[.07] bg-white p-5 md:p-6"><div className="flex items-start justify-between"><div><h2 className="font-semibold tracking-tight">Elegibilidade dos contatos</h2><p className="mt-1 text-xs text-black/40">Últimos 6 dias de operação</p></div><span className="rounded-lg bg-[#edf7ef] px-2.5 py-1 text-[11px] font-semibold text-[#258049]">+18,4%</span></div><div className="mt-6 h-[220px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f5b928" stopOpacity={.35}/><stop offset="100%" stopColor="#f5b928" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:11,fill:"#999"}} dy={10}/><Tooltip contentStyle={{borderRadius:12,border:"1px solid #eee",fontSize:12}}/><Area type="monotone" dataKey="value" stroke="#d79a07" strokeWidth={2.5} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></div>
  <div className="rounded-[22px] bg-[#1a1a1d] p-5 text-white md:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold tracking-tight">Funil de ontem</h2><p className="mt-1 text-xs text-white/35">Da comanda ao pós-venda</p></div><CheckCircle2 className="size-5 text-emerald-400" /></div><div className="mt-6 space-y-4">{funnel.map(([label,value,pct],i)=><div key={label}><div className="mb-1.5 flex items-center justify-between text-xs"><span className="text-white/60">{label}</span><span className="font-semibold">{value} <small className="ml-1 font-normal text-white/30">{pct}</small></span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#f5b928]" style={{width:`${[100,82,73,64][i]}%`}}/></div></div>)}</div></div></section>
  <section className="mt-5 grid gap-5 lg:grid-cols-3"><AlertCard icon={PackageSearch} title="Produtos novos" value="5" text="Precisam ser classificados antes do envio." tone="amber"/><AlertCard icon={Clock3} title="Contato recente" value="7" text="Protegidos pelo limite de 7 dias." tone="blue"/><AlertCard icon={ShieldCheck} title="X-Tudo excluídos" value="23" text="Removidos corretamente da fila House 190." tone="green"/></section>
</div>; }
function MetricCard({label,value,delta,tone}:{label:string;value:number;delta:string;tone:string}){const dark=tone==="dark",brand=tone==="brand";return <div className={`rounded-[20px] border p-5 ${dark?"border-[#171719] bg-[#171719] text-white":brand?"border-[#e3aa1f] bg-[#f5b928]":"border-black/[.07] bg-white"}`}><div className={`text-[11px] font-medium ${dark?"text-white/45":"text-black/42"}`}>{label}</div><div className="mt-5 flex items-end justify-between"><strong className="text-[32px] leading-none tracking-[-.05em]">{value}</strong><span className={`text-[10px] font-semibold ${dark?"text-white/35":"text-black/42"}`}>{delta}</span></div></div>}
function AlertCard({icon:Icon,title,value,text,tone}:{icon:typeof ShieldCheck;title:string;value:string;text:string;tone:string}){const colors=tone==="amber"?"bg-[#fff2ca] text-[#8a6200]":tone==="blue"?"bg-[#e8f0ff] text-[#466aa9]":"bg-[#e8f6eb] text-[#35804a]";return <div className="flex items-center gap-4 rounded-[18px] border border-black/[.07] bg-white p-4"><div className={`grid size-10 shrink-0 place-items-center rounded-xl ${colors}`}><Icon className="size-[18px]"/></div><div className="min-w-0"><div className="flex items-baseline gap-2"><p className="text-xs font-semibold">{title}</p><strong className="text-sm">{value}</strong></div><p className="mt-1 truncate text-[11px] text-black/40">{text}</p></div><ArrowRight className="ml-auto size-4 text-black/25"/></div>}
