import { AlertTriangle, ArrowRight, DatabaseZap, LoaderCircle, PackageSearch, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { useCrmData } from "@/context/CrmDataContext";

export function DashboardPage(){const{orders,products,queue,loading,error,lastImportAt}=useCrmData();const identified=orders.filter(o=>o.maskedPhone).length;const house=orders.filter(o=>o.brand==="HOUSE190").length;const eligible=orders.filter(o=>o.eligible).length;const sent=queue.filter(q=>q.status==="sent").length;const unmapped=products.filter(p=>p.brand==="UNMAPPED").length;const xtudo=orders.filter(o=>o.brand==="XTUDO").length;const recent=orders.filter(o=>o.reason==="FREQUENCY_CAP").length;const date=new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());return <div className="mx-auto max-w-[1440px] p-5 md:p-8 xl:p-10">
  <section className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 text-[11px] font-bold uppercase tracking-[.16em] text-black/38">{date}</div><h1 className="text-3xl font-semibold tracking-[-.045em] md:text-[40px]">Operação House 190</h1><p className="mt-2 text-sm text-black/48">{lastImportAt?`Última importação real: ${lastImportAt.toLocaleString("pt-BR")}`:"Nenhuma importação real concluída."}</p></div><div className="flex gap-2"><Link to="/clientes-ontem" className="rounded-xl border border-black/10 bg-white px-4 py-2.5 text-xs font-semibold">Ver pedidos</Link><Link to="/fila" className="flex items-center gap-2 rounded-xl bg-[#171719] px-4 py-2.5 text-xs font-semibold text-white">Revisar fila <ArrowRight className="size-4"/></Link></div></section>
  {loading&&<Notice icon={LoaderCircle} text="Carregando dados reais do Firebase…" spin/>}{error&&<Notice icon={AlertTriangle} text={error}/>} {!loading&&!error&&!lastImportAt&&<Notice icon={DatabaseZap} text="Aguardando a primeira execução da integração Takeat."/>}
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pedidos importados" value={orders.length}/><Metric label="Clientes identificados" value={identified}/><Metric label="House 190" value={house} brand/><Metric label="Elegíveis" value={eligible}/></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-[22px] border border-black/[.07] bg-white p-6"><h2 className="font-semibold">Funil da importação real</h2><div className="mt-6 space-y-5"><Funnel label="Pedidos Takeat" value={orders.length} max={Math.max(orders.length,1)}/><Funnel label="Clientes com telefone" value={identified} max={Math.max(orders.length,1)}/><Funnel label="Marca House 190" value={house} max={Math.max(orders.length,1)}/><Funnel label="Elegíveis pelas regras" value={eligible} max={Math.max(orders.length,1)}/><Funnel label="Mensagens enviadas" value={sent} max={Math.max(orders.length,1)}/></div></div><div className="rounded-[22px] bg-[#1a1a1d] p-6 text-white"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-emerald-400"/><h2 className="font-semibold">Proteções ativas</h2></div><div className="mt-6 grid gap-3"><Protection label="Produtos sem mapeamento" value={unmapped}/><Protection label="Pedidos X-Tudo excluídos" value={xtudo}/><Protection label="Bloqueados por frequência" value={recent}/><Protection label="Mensagens em fila" value={queue.length}/></div></div></section>
</div>}
function Notice({icon:Icon,text,spin=false}:{icon:typeof AlertTriangle;text:string;spin?:boolean}){return <div className="mt-7 flex items-center gap-3 rounded-2xl border border-[#e5ae25]/35 bg-[#fff7dc] p-4 text-xs text-[#765506]"><Icon className={`size-4 ${spin?"animate-spin":""}`}/><strong>{text}</strong></div>}
function Metric({label,value,brand=false}:{label:string;value:number;brand?:boolean}){return <div className={`rounded-[20px] border p-5 ${brand?"border-[#e3aa1f] bg-[#f5b928]":"border-black/[.07] bg-white"}`}><p className="text-[11px] font-medium text-black/42">{label}</p><strong className="mt-5 block text-[32px] leading-none tracking-[-.05em]">{value}</strong></div>}
function Funnel({label,value,max}:{label:string;value:number;max:number}){return <div><div className="mb-2 flex justify-between text-xs"><span className="text-black/50">{label}</span><strong>{value}</strong></div><div className="h-2 rounded-full bg-black/[.06]"><div className="h-2 rounded-full bg-[#f5b928]" style={{width:`${Math.max(value?4:0,value/max*100)}%`}}/></div></div>}
function Protection({label,value}:{label:string;value:number}){return <div className="flex items-center justify-between rounded-xl bg-white/[.06] px-4 py-3 text-xs"><span className="text-white/55">{label}</span><strong>{value}</strong></div>}
