import { useState } from "react";
import { AlertTriangle, RefreshCw, Search } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { PageHeader } from "@/components/ui/PageHeader";
import { products as initialProducts } from "@/data/mock";
import { money } from "@/lib/utils";
import type { ProductBrand } from "@/types/domain";

const brands=["HOUSE190","XTUDO","OTHER","IGNORE","UNMAPPED"] as const;
type ProductRow={id:string;name:string;category:string;price:number;brand:ProductBrand;available:boolean};
export function ProductsPage(){const [products,setProducts]=useState<ProductRow[]>(initialProducts.map(x=>({...x})));const [query,setQuery]=useState("");return <div className="mx-auto max-w-[1280px] p-5 md:p-8 xl:p-10"><PageHeader eyebrow="Regra central" title="Produtos & marcas" description="O ID real do produto Takeat é a fonte de verdade. Produtos novos bloqueiam automaticamente o envio." actions={<button className="rounded-xl bg-[#171719] px-4 py-2.5 text-xs font-semibold text-white"><RefreshCw className="mr-2 inline size-4"/>Sincronizar Takeat</button>}/><div className="mt-7 flex items-center gap-3 rounded-2xl border border-[#e5ae25]/35 bg-[#fff7dc] p-4 text-xs text-[#765506]"><AlertTriangle className="size-4"/><strong>1 produto precisa de classificação.</strong> Pedidos afetados permanecem em revisão necessária.</div><div className="mt-5 rounded-[22px] border border-black/[.07] bg-white"><div className="flex items-center justify-between border-b border-black/[.07] p-4"><label className="flex items-center gap-2 rounded-xl border border-black/10 px-3 py-2"><Search className="size-4 text-black/35"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto" className="bg-transparent text-xs outline-none"/></label><Badge tone="green">5 classificados</Badge></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-black/[.06] text-[10px] uppercase tracking-wider text-black/35"><th className="p-4">Produto</th><th>Categoria</th><th>Preço</th><th>ID Takeat</th><th>Marca</th></tr></thead><tbody>{products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=><tr key={p.id} className="border-b border-black/[.055] text-xs last:border-0"><td className="p-4 font-semibold">{p.name}</td><td className="text-black/48">{p.category}</td><td>{money(p.price)}</td><td className="font-mono text-[10px] text-black/38">{p.id}</td><td><select value={p.brand} onChange={e=>setProducts(rows=>rows.map(x=>x.id===p.id?{...x,brand:e.target.value as ProductBrand}:x))} className={`rounded-xl border px-3 py-2 text-[10px] font-bold outline-none ${p.brand==="UNMAPPED"?"border-[#e5ae25] bg-[#fff7dc]":"border-black/10 bg-white"}`}>{brands.map(b=><option key={b}>{b}</option>)}</select></td></tr>)}</tbody></table></div></div></div>}
