import { useState } from "react";
import { DatabaseZap,RefreshCw,Search } from "lucide-react";
import { doc,serverTimestamp,setDoc } from "firebase/firestore";
import { PageHeader } from "@/components/ui/PageHeader";
import { useCrmData } from "@/context/CrmDataContext";
import { db } from "@/lib/firebase";
import { money } from "@/lib/utils";
import type { ProductBrand } from "@/types/domain";
const brands:ProductBrand[]=["HOUSE190","XTUDO","OTHER","IGNORE","UNMAPPED"];
export function ProductsPage(){const{products,loading}=useCrmData();const[query,setQuery]=useState("");const[busy,setBusy]=useState<string|null>(null);async function map(id:string,name:string,brand:ProductBrand){if(!db)return;setBusy(id);try{const now=serverTimestamp();await Promise.all([setDoc(doc(db,"productBrandMappings",id),{productId:id,productName:name,brand,updatedAt:now},{merge:true}),setDoc(doc(db,"products",id),{brand,updatedAt:now},{merge:true}),setDoc(doc(db,"auditLogs",crypto.randomUUID()),{action:"PRODUCT_BRAND_CHANGED",productId:id,productName:name,brand,createdAt:now})]);}finally{setBusy(null)}}return <div className="mx-auto max-w-[1200px] p-5 md:p-8 xl:p-10"><PageHeader eyebrow="Catálogo Takeat" title="Produtos & marcas" description="Somente produtos sincronizados da unidade real aparecem nesta tela." actions={<button disabled className="rounded-xl bg-[#171719] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40"><RefreshCw className="mr-2 inline size-4"/>Sincronização automática</button>}/><div className="mt-7 rounded-[22px] border border-black/[.07] bg-white"><div className="flex justify-end border-b border-black/[.07] p-4"><label className="flex items-center gap-2 rounded-xl border border-black/10 px-3 py-2"><Search className="size-4 text-black/35"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto real" className="bg-transparent text-xs outline-none"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-black/[.06] text-[10px] uppercase tracking-wider text-black/35"><th className="p-4">Produto</th><th>Categoria</th><th>Preço</th><th>ID Takeat</th><th>Marca</th></tr></thead><tbody>{products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=><tr key={p.id} className="border-b border-black/[.055] text-xs last:border-0"><td className="p-4 font-semibold">{p.name}</td><td className="text-black/48">{p.category}</td><td>{money(p.price)}</td><td className="font-mono text-[10px] text-black/38">{p.id}</td><td><select disabled={busy===p.id} value={p.brand} onChange={e=>map(p.id,p.name,e.target.value as ProductBrand)} className={`rounded-xl border px-3 py-2 text-[10px] font-bold ${p.brand==="UNMAPPED"?"border-[#e5ae25] bg-[#fff7dc]":"border-black/10 bg-white"}`}>{brands.map(b=><option key={b}>{b}</option>)}</select></td></tr>)}</tbody></table>{!loading&&!products.length&&<div className="grid place-items-center py-20 text-center"><DatabaseZap className="size-8 text-black/20"/><p className="mt-3 text-sm font-medium">Nenhum produto real sincronizado.</p><p className="mt-1 text-xs text-black/40">A sincronização ocorrerá após configurar a Takeat.</p></div>}</div></div></div>}
