import { useMemo,useState } from "react";
import { DatabaseZap,Search } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { PageHeader } from "@/components/ui/PageHeader";
import { useCrmData } from "@/context/CrmDataContext";
import { money } from "@/lib/utils";
const tone={HOUSE190:"green",XTUDO:"red",MIXED:"amber",OTHER:"gray",UNMAPPED:"blue"} as const;
export function YesterdayCustomersPage(){const{orders,loading}=useCrmData();const[query,setQuery]=useState("");const rows=useMemo(()=>orders.filter(o=>`${o.customerName} ${o.maskedPhone??""} ${o.products.map(p=>p.name).join(" ")}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.purchaseAt?.getTime()??0)-(a.purchaseAt?.getTime()??0)),[orders,query]);return <div className="mx-auto max-w-[1440px] p-5 md:p-8 xl:p-10"><PageHeader eyebrow="Dados importados" title="Clientes e pedidos" description="Somente informações recebidas da Takeat e persistidas no Firebase são exibidas aqui."/><div className="mt-7 rounded-[22px] border border-black/[.07] bg-white"><div className="flex justify-end border-b border-black/[.07] p-4"><label className="flex items-center gap-2 rounded-xl border border-black/10 px-3 py-2"><Search className="size-4 text-black/35"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nos dados reais" className="bg-transparent text-xs outline-none"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead><tr className="border-b border-black/[.06] text-[10px] uppercase tracking-wider text-black/35"><th className="p-4">Cliente</th><th>Compra</th><th>Valor</th><th>Canal</th><th>Produtos</th><th>Marca</th><th>Decisão</th></tr></thead><tbody>{rows.map(o=><tr key={o.id} className="border-b border-black/[.055] text-xs last:border-0"><td className="p-4"><p className="font-semibold">{o.customerName}</p><p className="mt-1 text-[10px] text-black/35">{o.maskedPhone??"Telefone ausente"}</p></td><td>{o.purchaseAt?.toLocaleString("pt-BR")??"Não informada"}</td><td>{money(o.total)}</td><td><Badge>{o.channel}</Badge></td><td className="max-w-[220px] truncate pr-4 text-black/55">{o.products.map(p=>`${p.amount}× ${p.name}`).join(", ")||"Sem itens"}</td><td><Badge tone={tone[o.brand]}>{o.brand}</Badge></td><td><p className="font-medium">{o.eligible?"Elegível":"Excluído"}</p>{o.reason&&<p className="mt-1 text-[10px] text-black/38">{o.reason}</p>}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<Empty text="Nenhum pedido real foi importado ainda."/>}</div></div></div>}
function Empty({text}:{text:string}){return <div className="grid place-items-center py-20 text-center"><DatabaseZap className="size-8 text-black/20"/><p className="mt-3 text-sm font-medium">{text}</p><p className="mt-1 text-xs text-black/40">Configure a integração e execute o fluxo diário.</p></div>}
